# Generated by Django 2.2.4 on 2019-08-15 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='campus',
            field=models.CharField(choices=[('ZGC', '中关村'), ('LX', '良乡')], default='LX', max_length=5, verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='record',
            name='appointment_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='campus',
            field=models.CharField(choices=[('ZGC', '中关村'), ('LX', '良乡')], max_length=50, verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(default='default description', max_length=300, verbose_name='问题自述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '上单未解决'), (1, '预约待确认'), (2, '预约已确认'), (3, '预约已驳回'), (4, '登记待受理'), (5, '正在处理'), (6, '已解决问题'), (7, '建议返厂'), (8, '扔给明天')], default=1, verbose_name='状态'),
        ),
    ]
