# Generated by Django 2.2.4 on 2019-08-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190815_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appointment_time',
            field=models.DateField(blank=True, null=True, verbose_name='预约日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='campus',
            field=models.CharField(choices=[('ZGC', '中关村'), ('LX', '良乡')], default='LX', max_length=50, verbose_name='校区'),
        ),
    ]
