# Generated by Django 2.2.4 on 2019-08-15 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20190815_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appointment_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约日期'),
            preserve_default=False,
        ),
    ]
