# Generated by Django 2.2.4 on 2019-08-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20190815_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='正常服务', max_length=30, verbose_name='名称')),
                ('start', models.DateField(verbose_name='开始日期')),
                ('end', models.DateField(verbose_name='结束日期')),
                ('capacity', models.IntegerField(verbose_name='可服务人数')),
            ],
        ),
    ]
