# Generated by Django 2.2.4 on 2019-08-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_servetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServeTime',
            new_name='Date',
        ),
    ]
