# Generated by Django 2.2.4 on 2019-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_remove_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='start',
            field=models.DateField(unique_for_date=True, verbose_name='开始日期'),
        ),
    ]
