# Generated by Django 2.2.4 on 2019-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20190816_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='start',
            field=models.DateField(unique=True, verbose_name='开始日期'),
        ),
    ]
