# Generated by Django 2.2.4 on 2019-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20190816_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='可服务人数'),
        ),
    ]
