# Generated by Django 2.2.4 on 2019-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_date_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='已使用容量'),
        ),
    ]
