# Generated by Django 2.2.4 on 2019-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_date_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tag', models.CharField(default='', max_length=5, verbose_name='类型')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastEditedTime', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('expireTime', models.DateTimeField(verbose_name='失效时间')),
            ],
        ),
    ]
