# Generated by Django 2.2.5 on 2019-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_auto_20190818_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='校区名称')),
                ('address', models.CharField(max_length=100, verbose_name='诊所地址')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tag',
            field=models.CharField(choices=[('AN', '普通公告'), ('TOC', '免责声明')], max_length=5, verbose_name='类型'),
        ),
    ]
