# Generated by Django 2.2.5 on 2019-09-25 14:19

from django.db import migrations


def insert_campus(apps, schema_editor):
    Campus = apps.get_model('clinic', 'Campus')
    lx = Campus()
    lx.name = '良乡校区'
    lx.address = '徐特立图书馆311G'
    lx.save()
    zgc = Campus()
    zgc.name = '中关村校区'
    zgc.address = '中关村体育馆南厅夹层J12'
    zgc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_auto_20190925_2218'),
    ]

    operations = [
        migrations.RunPython(insert_campus),
    ]
