# Generated by Django 2.2.5 on 2019-09-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_auto_20190925_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='count',
        ),
        migrations.RemoveField(
            model_name='date',
            name='finish',
        ),
    ]
