# Generated by Django 2.2.5 on 2019-09-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_auto_20190925_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.Campus'),
        ),
    ]
