# Generated by Django 2.2.5 on 2019-09-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_auto_20190925_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='start',
            new_name='date',
        ),
    ]
