# Generated by Django 2.2.5 on 2019-09-26 01:55

from django.db import migrations

def link_campus(apps, schema_editor):
    Campus = apps.get_model('clinic', 'Campus')
    Record = apps.get_model('clinic', 'Record')
    ClinicUser = apps.get_model('clinic', 'ClinicUser')
    lx = Campus.objects.get(name='良乡校区')
    zgc = Campus.objects.get(name='中关村校区')
    Record.objects.filter(campus='LX').update(campus_link=lx)
    Record.objects.filter(campus='ZGC').update(campus_link=zgc)
    ClinicUser.objects.filter(campus='LX').update(campus_link=lx)
    ClinicUser.objects.filter(campus='ZGC').update(campus_link=zgc)


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_auto_20190926_0955'),
    ]

    operations = [
        migrations.RunPython(link_campus),
    ]
