# Generated by Django 2.2.5 on 2019-09-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20190926_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicuser',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='record',
            name='campus',
        ),
    ]
