# Generated by Django 2.2.4 on 2019-09-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_auto_20190927_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='realname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='record',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='clinic.Campus', verbose_name='校区'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='realname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
    ]
