# Generated by Django 2.2.4 on 2019-10-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_auto_20190927_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['-date']},
        ),
    ]
