# Generated by Django 2.2.4 on 2019-10-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_auto_20191006_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date']},
        ),
    ]
