# Generated by Django 2.2.5 on 2019-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_auto_20191006_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='announcement',
            name='piority',
            field=models.PositiveIntegerField(default=1, verbose_name='显示优先级'),
        ),
    ]
