# Generated by Django 2.2.4 on 2019-10-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0033_auto_20191007_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['priority', '-createdTime']},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='piority',
            new_name='priority',
        ),
    ]
