# Generated by Django 2.2.5 on 2019-10-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_auto_20191008_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='brief',
            field=models.TextField(blank=True, default='', verbose_name='内容概括'),
        ),
    ]
