# Generated by Django 2.2.4 on 2019-10-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0035_announcement_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tag',
            field=models.CharField(choices=[('AN', '普通公告'), ('TOC', '免责声明'), ('TA', '置顶公告')], max_length=5, verbose_name='类型'),
        ),
    ]
