# Generated by Django 2.2.4 on 2019-10-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0038_auto_20191015_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('campus', 'date')},
        ),
    ]
