# Generated by Django 2.2.4 on 2019-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0039_auto_20191016_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tag',
            field=models.CharField(choices=[('AN', '普通公告'), ('TOS', '免责声明'), ('TA', '置顶公告')], max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '上单未解决'), (1, '预约待确认'), (2, '预约已确认'), (3, '预约已驳回'), (4, '登记待受理'), (5, '正在处理'), (6, '已解决问题'), (7, '建议返厂'), (8, '扔给明天'), (9, '未到诊所')], default=1, verbose_name='状态'),
        ),
    ]
