# Generated by Django 4.2.4 on 2023-08-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0040_auto_20191017_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['priority', '-createdTime'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date'], 'verbose_name': '服务时间', 'verbose_name_plural': '服务时间'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-id'], 'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
        migrations.AlterField(
            model_name='clinicuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_taken',
            field=models.BooleanField(default=True, verbose_name='是否取走'),
        ),
    ]
