# Generated by Django 4.2.4 on 2023-08-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0041_alter_announcement_options_alter_campus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicuser',
            options={'ordering': ['id']},
        ),
    ]
