name: Build Docker Image & Push to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push_to_ghcr:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull submodules
        run: git submodule init && git submodule update --remote

      - name: Save Docker Image
        run: |
          docker build . -t ghcr.io/dustin-jiang/clinic_django/clinic_django:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/dustin-jiang/clinic_django/clinic_django:latest